# 在线作业
apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-iperf
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-iperf
  template:
    metadata:
      labels:
        app: online-iperf
      annotations:
        volcano.sh/qos-level: "HLS" # 标识在线作业
    spec:
      containers:
        - name: container-1
          image: volcanosh/iperf
          command:
            - /bin/sh
            - -c
            - |
              iperf -c $node_ip -i 1 -t 30 -f mb # 模拟消耗带宽
              echo finished...
              sleep 1000000
---
# 离线作业
apiVersion: apps/v1
kind: Deployment
metadata:
  name: offline-iperf
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offline-iperf
  template:
    metadata:
      labels:
        app: offline-iperf
      annotations:
        volcano.sh/qos-level: "BE" # 标识离线作业
    spec:
      containers:
        - name: container-1
          image: volcanosh/iperf
          command:
            - /bin/sh
            - -c
            - |
              iperf -c $node_ip -i 1 -t 30 -f mb # 模拟消耗带宽
              echo finished...
              sleep 1000000
